# SQLITE3

In [1]:
import sqlite3 as sl
import pandas as pd

In [2]:
db_name = "test_connection.db" # указываем имя бд
con = sl.connect(db_name) # подключение

In [3]:
data_to_db = pd.read_csv("forbes_richest_atheletes.csv", index_col="S.NO")
data_to_db

,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
S.NO,,,,,,,
1,Mike Tyson,USA,1,NaN,boxing,1990,28.6
2,Buster Douglas,USA,2,NaN,boxing,1990,26.0
3,Sugar Ray Leonard,USA,3,NaN,boxing,1990,13.0
4,Ayrton Senna,Brazil,4,NaN,auto racing,1990,10.0
5,Alain Prost,France,5,NaN,auto racing,1990,9.0
...,...,...,...,...,...,...,...
297,Stephen Curry,USA,6,9,Basketball,2020,74.4
298,Kevin Durant,USA,7,10,Basketball,2020,63.9
299,Tiger Woods,USA,8,11,Golf,2020,62.3
300,Kirk Cousins,USA,9,>100,American Football,2020,60.5
301,Carson Wentz,USA,10,>100,American Football,2020,59.1

In [6]:
data_to_db.to_sql('athletes', con=con)

301

In [7]:
READ_ALL = "SELECT * FROM athletes;"
data = con.execute(READ_ALL)

for row in data:
  print(row)

(1, 'Mike Tyson', 'USA', 1, None, 'boxing', 1990, 28.6)
(2, 'Buster Douglas', 'USA', 2, None, 'boxing', 1990, 26.0)
(3, 'Sugar Ray Leonard', 'USA', 3, None, 'boxing', 1990, 13.0)
(4, 'Ayrton Senna', 'Brazil', 4, None, 'auto racing', 1990, 10.0)
(5, 'Alain Prost', 'France', 5, None, 'auto racing', 1990, 9.0)
(6, 'Jack Nicklaus', 'USA', 6, None, 'golf', 1990, 8.6)
(7, 'Greg Norman', 'Australia', 7, None, 'golf', 1990, 8.5)
(8, 'Michael Jordan', 'USA', 8, None, 'basketball', 1990, 8.1)
(9, 'Arnold Palmer', 'USA', 8, None, 'golf', 1990, 8.1)
(10, 'Evander Holyfield', 'USA', 8, None, 'boxing', 1990, 8.1)
(11, 'Evander Holyfield', 'USA', 1, '8', 'boxing', 1991, 60.5)
(12, 'Mike Tyson', 'USA', 2, '1', 'boxing', 1991, 31.5)
(13, 'Michael Jordan', 'USA', 3, '8', 'basketball', 1991, 16.0)
(14, 'George Foreman', 'USA', 4, '>30', 'boxing', 1991, 14.5)
(15, 'Ayrton Senna', 'Brazil', 5, '4', 'auto racing', 1991, 13.0)
(16, 'Alain Prost', 'France', 6, '5', 'auto racing', 1991, 11.0)
(17, 'Donovan "Razor" Ruddock', 'Canada', 7, '>30', 'boxing', 1991, 10.2)
(18, 'Arnold Palmer', 'USA', 8, '8', 'golf', 1991, 9.3)
(19, 'Nigel Mansell', 'UK', 9, '12', 'auto racing', 1991, 9.0)
(20, 'Sugar Ray Leonard', 'USA', 10, '6', 'golf', 1991, 8.5)
(21, 'Michael Jordan', 'USA', 1, '3', 'Basketball', 1992, 35.9)
(22, 'Evander Holyfield', 'USA', 2, '1', 'Boxing', 1992, 28.0)
(23, 'Ayrton Senna', 'Brazil', 3, '5', 'Auto Racing', 1992, 22.0)
(24, 'Nigel Mansell', 'UK', 4, '9', 'Auto Racing', 1992, 14.5)
(25, 'Arnold Palmer', 'USA', 5, '8', 'Golf', 1992, 11.1)
(26, 'Andre Agassi', 'USA', 6, '17', 'Tennis', 1992, 11.0)
(27, 'Joe Montana', 'USA', 7, '13', 'NFL', 1992, 9.5)
(28, 'Sugar Ray Leonard', 'USA', 8, '10', 'Golf', 1992, 9.2)
(29, 'Jim Courier', 'USA', 9, '>40', 'Tennis', 1992, 9.0)
(30, 'Monica Seles', 'USA', 10, '12', 'Tennis', 1992, 8.5)
(31, 'Michael Jordan', 'USA', 1, '1', 'Basketball', 1993, 36.0)
(32, 'Riddick Bowe', 'USA', 2, '>40', 'Boxing', 1993, 25.0)
(33, 'Ayrton Senna', 'Brazil', 3, '3', 'Auto racing', 1993, 18.5)
(34, 'Alain Prost', 'France', 4, '>40', 'Auto Racing', 1993, 16.0)
(35, 'George Foreman', 'USA', 5, '19', 'Boxing', 1993, 15.8)
(36, "Shaquille O'Neal", 'USA', 6, '>40', 'NBA', 1993, 15.2)
(37, 'Lennox Lewis', 'USA', 7, '>40', 'Boxing', 1993, 15.0)
(38, 'Cecil Fielder', 'USA', 8, '40', 'Baseball', 1993, 12.7)
(39, 'Jim Courier', 'USA', 9, '9', 'Tennis', 1993, 12.6)
(40, 'Joe Montana', 'USA', 10, '7', 'NFL', 1993, 11.5)
(41, 'Michael Jordan', 'USA', 1, '1', 'Basketball', 1994, 30.0)
(42, "Shaq O'Neal", 'USA', 2, '6', 'Basketball', 1994, 16.7)
(43, 'Jack Nicklaus', 'USA', 3, '13', 'Golf', 1994, 14.8)
(44, 'Arnold Palmer', 'USA', 4, '11', 'Golf', 1994, 13.6)
(45, 'Gerhard Berger', 'Austria', 5, '30', 'Auto Racing', 1994, 13.5)
(46, 'Wayne Gretzky', 'Canada', 5, '22', 'Ice Hockey', 1994, 13.5)
(47, 'Michael Moorer', 'USA', 7, '>40', 'Boxing', 1994, 12.1)
(48, 'Evander Holyfield', 'USA', 8, '12', 'Boxing', 1994, 12.0)
(49, 'Andre Agassi', 'USA', 9, '20', 'Tennis', 1994, 11.4)
(50, 'Nigel Mansell', 'UK', 10, '19', 'Auto Racing', 1994, 11.3)
(51, 'Michael Jordan', 'USA', 1, '1', 'basketball', 1995, 43.9)
(52, 'Mike Tyson', 'USA', 2, 'not ranked', 'boxing', 1995, 40.0)
(53, 'Deion Sanders', 'USA', 3, '38', 'American Football / Baseball', 1995, 22.5)
(54, 'Riddick Bowe', 'USA', 4, 'not ranked', 'boxing', 1995, 22.2)
(55, "Shaquille O'Neal", 'USA', 5, '2', 'basketball', 1995, 21.9)
(56, 'George Foreman', 'USA', 6, '15', 'boxing', 1995, 18.0)
(57, 'Andre Agassi', 'USA', 7, '9', 'tennis', 1995, 16.0)
(58, 'Sugar Ray Leonard', 'USA', 8, '3', 'golf', 1995, 15.1)
(59, 'Michael Schumacher', 'Germany', 9, '30', 'auto racing', 1995, 15.0)
(60, 'Wayne Gretzky', 'Canada', 10, '5', 'ice hockey', 1995, 14.5)
(61, 'Mike Tyson', 'USA', 1, '2', 'Boxing', 1996, 75.0)
(62, 'Michael Jordan', 'USA', 2, '1', 'Basketball', 1996, 52.6)
(63, 'Michael Schumacher', 'Germany', 3, '9', 'F1 Motorsports', 1996, 33.0)
(64, "Shaquille O'Neal", 'USA', 4, '5', 'Basketball', 1996, 24.4)
(65, 'Emmit Smith', 'USA', 5, 'not ranked', 'NFL', 1996, 16.5)
(66, 'Evander Holyfield', 'USA', 6, '14', 'Boxing', 1996, 15.5)
(67, 'Andre Agassi', 'USA', 7, '7', 'Tennis', 1996, 15.2)
(68, 'Arnold Palmer', 'USA', 8, '11', 'Golf', 1996, 15.1)
(69, 'Dennis Rodman', 'USA', 9, 'not ranked', 'Basketball', 1996, 12.9)
(70, 'Patrick Ewing', 'USA', 9, '19', 'Basketball', 1996, 12.9)
(71, 'Michael Jordan', 'USA', 1, '2', 'Basketball', 1997, 78.3)
(72, 'Evander Holyfield', 'USA', 2, '6', 'Boxing', 1997, 54.3)
(73, 'Oscar De La Hoya', 'USA', 3, '17', 'Boxing', 1997, 38.0)
(74, 'Michael Schumacher', 'Germany', 4, '3', 'F1 Motorsports', 1997, 35.0)
(75, 'Mike Tyson', 'USA', 5, '1', 'Boxing', 1997, 27.0)
(76, 'Tiger Woods', 'USA', 6, '26', 'Golf', 1997, 26.1)
(77, "Shaquille O'Neal", 'USA', 7, '4', 'Basketball', 1997, 25.4)
(78, 'Dale Earnhardt', 'USA', 8, '20', 'NASCAR', 1997, 19.1)
(79, 'Joe Sakic', 'Canada', 9, 'none', 'Hockey', 1997, 17.9)
(80, 'Grant Hill', 'USA', 10, '18', 'Basketball', 1997, 17.0)
(81, 'Michael Jordan', 'USA', 1, None, 'Basketball', 1998, 69.0)
(82, 'Michael Schumacher', 'Germany', 2, None, 'F1 Motorsports', 1998, 38.0)
(83, 'Sergei Federov', 'Russia', 3, None, 'Ice Hockey', 1998, 29.8)
(84, 'Tiger Woods', 'USA', 4, None, 'Golf', 1998, 26.8)
(85, 'Dale Earnhardt', 'USA', 5, None, 'NASCAR', 1998, 24.1)
(86, 'Grant Hill', 'USA', 6, None, 'Basketball', 1998, 21.6)
(87, 'Oscar De La Hoya', 'USA', 7, None, 'Boxing', 1998, 18.5)
(88, 'Patrick Ewing', 'USA', 8, None, 'Basketball', 1998, 18.3)
(89, 'Arnold Palmer', 'USA', 9, None, 'Golf', 1998, 18.1)
(90, 'Gary Sheffield', 'USA', 10, None, 'Baseball', 1998, 17.2)
(91, 'Michael Schumacher', 'Germany', 1, '2', 'Auto Racing', 1999, 49.0)
(92, 'Tiger Woods', 'USA', 2, '4', 'Golf', 1999, 47.0)
(93, 'Oscar De La Hoya', 'USA', 3, '7', 'Boxing', 1999, 43.5)
(94, 'Michael Jordan', 'USA', 4, '1', 'Basketball', 1999, 40.0)
(95, 'Evander Holyfield', 'USA', 5, '>10', 'Boxing', 1999, 35.5)
(96, 'Mike Tyson', 'USA', 6, '>10', 'Boxing', 1999, 33.0)
(97, "Shaq O'Neal", 'USA', 7, '>10', 'Basketball', 1999, 31.0)
(98, 'Lennox Lewis', 'USA', 8, '>10', 'Boxing', 1999, 29.0)
(99, 'Dale Earnhardt', 'USA', 9, '5', 'Auto Racing', 1999, 26.5)
(100, 'Grant Hill', 'USA', 10, '6', 'Basketball', 1999, 23.0)
(101, 'Michael Schumacher', 'Germany', 1, '1', 'Auto Racing', 2000, 59.0)
(102, 'Tiger Woods', 'USA', 2, '2', 'Golf', 2000, 53.0)
(103, 'Mike Tyson', 'USA', 3, '6', 'Boxing', 2000, 48.0)
(104, 'Michael Jordan', 'USA', 4, '4', 'Basketball', 2000, 37.0)
(105, 'Grant Hill', 'USA', 5, '10', 'Basketball', 2000, 26.0)
(106, 'Dale Earnhardt', 'USA', 6, '9', 'Auto Racing (Nascar)', 2000, 24.5)
(107, "Shaq O'Neal", 'USA', 7, '7', 'Basketball', 2000, 24.0)
(108, 'Lennox Lewis', 'USA', 8, '8', 'Boxing', 2000, 23.0)
(109, 'Oscar De La Hoya', 'USA', 9, '3', 'Boxing', 2000, 23.0)
(110, 'Kevin Garnett', 'USA', 10, '>10', 'Basketball', 2000, 21.0)
(111, 'Tiger Woods', 'USA', 1, '2', 'Golf', 2002, 69.0)
(112, 'Michael Schumacher', 'Germany', 2, '1', 'F1 Motorsports', 2002, 67.0)
(113, 'Michael Jordan', 'USA', 3, '4', 'Basketball', 2002, 36.0)
(114, 'Lennox Lewis', 'USA', 4, '8', 'Boxing', 2002, 28.0)
(115, 'Grant Hill', 'USA', 5, '5', 'Basketball', 2002, 24.0)
(116, "Shaquille O'Neal", 'USA', 5, '7', 'Basketball', 2002, 24.0)
(117, 'Mike Tyson', 'USA', 7, '3', 'Boxing', 2002, 23.0)
(118, 'Kevin Garnett', 'USA', 7, '10', 'Basketball', 2002, 23.0)
(119, 'Kobe Bryant', 'USA', 9, '>10', 'Basketball', 2002, 22.0)
(120, 'Jacques Villeneuve', 'Canada', 10, '>10', 'Auto Racing', 2002, 20.0)
(121, 'Jeff Gordon', 'USA', 10, '>10', 'Auto Racing (Nascar)', 2002, 20.0)
(122, 'Tiger Woods', 'USA', 1, '1', 'Golf', 2003, 78.0)
(123, 'Michael Schumacher', 'Germany', 2, '2', 'F1 Motorsports', 2003, 75.0)
(124, 'Michael Jordan', 'USA', 3, '3', 'Basketball', 2003, 35.0)
(125, "Shaq O'Neal", 'USA', 4, '5', 'Basketball', 2003, 30.5)
(126, 'Oscar De La Hoya', 'USA', 5, '>10', 'Boxing', 2003, 30.0)
(127, 'Kevin Garnett', 'USA', 6, '7', 'Basketball', 2003, 28.0)
(128, 'Alex Rodriguez', 'USA', 7, '>10', 'Baseball', 2003, 26.0)
(129, 'Grant Hill', 'USA', 8, '5', 'Basketball', 2003, 25.5)
(130, 'Andre Agassi', 'USA', 9, '>10', 'Tennis', 2003, 24.0)
(131, 'Jacques Villeneuve', 'Canada', 10, '10', 'Auto Racing', 2003, 23.0)
(132, 'Tiger Woods', 'USA', 1, '1', 'golf', 2004, 80.3)
(133, 'Michael Schumacher', 'Germany', 2, '2', 'F1 racing', 2004, 80.0)
(134, 'Peyton Manning', 'USA', 3, '>10', 'American Football', 2004, 42.0)
(135, 'Michael Jordan', 'USA', 4, '3', 'basketball', 2004, 35.0)
(136, "Shaquille O'Neal", 'USA', 5, '4', 'basketball', 2004, 31.9)
(137, 'Kevin Garnett', 'USA', 6, '6', 'basketball', 2004, 29.7)
(138, 'Andre Agassi', 'USA', 7, '9', 'tennis', 2004, 28.2)
(139, 'David Beckham', 'UK', 8, '>10', 'soccer', 2004, 28.0)
(140, 'Alex Rodriguez', 'USA', 9, '7', 'baseball', 2004, 26.2)
(141, 'Kobe Bryant', 'USA', 10, '>10', 'basketball', 2004, 26.1)
(142, 'Tiger Woods', 'USA', 1, '1', 'golf', 2005, 87.0)
(143, 'Michael Schumacher', 'Germany', 2, '2', 'F1 racing', 2005, 60.0)
(144, 'Oscar De La Hoya', 'USA', 3, '>10', 'boxing', 2005, 38.0)
(145, 'Michael Vick', 'USA', 4, '>10', 'American Football', 2005, 37.5)
(146, "Shaquille O'Neal", 'USA', 5, '5', 'basketball', 2005, 33.4)
(147, 'Michael Jordan', 'USA', 6, '4', 'basketball', 2005, 33.0)
(148, 'David Beckham', 'UK', 7, '8', 'soccer', 2005, 32.5)
(149, 'Kobe Bryant', 'USA', 8, '10', 'basketball', 2005, 28.8)
(150, 'Lance Armstrong', 'USA', 9, '>10', 'cycling', 2005, 28.0)
(151, 'Valentino Rossi', 'Italy', 9, '>10', 'motorcycle gp', 2005, 28.0)
(152, 'Tiger Woods', 'USA', 1, '1', 'golf', 2006, 90.0)
(153, 'Michael Schumacher', 'Germany', 2, '2', 'F1 racing', 2006, 58.0)
(154, 'Muhammad Ali', 'USA', 3, '>10', 'boxing', 2006, 55.0)
(155, 'Phil Mickelson', 'USA', 4, '>10', 'golf', 2006, 47.0)
(156, 'Michael Jordan', 'USA', 5, '6', 'basketball', 2006, 32.0)
(157, 'Kobe Bryant', 'USA', 6, '8', 'basketball', 2006, 31.0)
(158, "Shaquille O'Neal", 'USA', 7, '5', 'basketball', 2006, 30.0)
(159, 'Valentino Rossi', 'Italy', 8, '9', 'motorcycle gp', 2006, 30.0)
(160, 'Alex Rodriguez', 'USA', 9, '>10', 'baseball', 2006, 29.0)
(161, 'Tom Brady', 'USA', 9, '>10', 'American Football', 2006, 29.0)
(162, 'Tiger Woods', 'USA', 1, '1', 'golf', 2007, 100.0)
(163, 'Oscar De La Hoya', 'USA', 2, '>10', 'boxing', 2007, 43.0)
(164, 'Phil Mickelson', 'USA', 3, '4', 'golf', 2007, 42.0)
(165, 'Kimi Raikkonen', 'Finland', 4, '>10', 'F1 racing', 2007, 40.0)
(166, 'Michael Schumacher', 'Germany', 5, '2', 'F1 racing', 2007, 36.0)
(167, 'David Beckham', 'UK', 6, '>10', 'soccer', 2007, 33.0)
(168, 'Kobe Bryant', 'USA', 6, '>10', 'basketball', 2007, 33.0)
(169, "Shaquille O'Neal", 'USA', 8, '7', 'basketball', 2007, 32.0)
(170, 'Ronaldinho', 'Brazil', 9, '>10', 'soccer', 2007, 31.0)
(171, 'Michael Jordan', 'USA', 9, '5', 'basketball', 2007, 31.0)
(172, 'Tiger Woods', 'USA', 1, '1', 'golf', 2008, 115.0)
(173, 'David Beckham', 'UK', 2, '6', 'soccer', 2008, 50.0)
(174, 'Michael Jordan', 'USA', 3, '9', 'basketball', 2008, 45.0)
(175, 'Phil Mickelson', 'USA', 3, '3', 'golf', 2008, 45.0)
(176, 'Kimi Raikkonen', 'Finland', 5, '4', 'F1 racing', 2008, 44.0)
(177, 'Kobe Bryant', 'USA', 6, '7', 'basketball', 2008, 39.0)
(178, 'LeBron James', 'USA', 7, '>10', 'basketball', 2008, 38.0)
(179, 'Ronaldinho', 'Brazil', 8, '9', 'soccer', 2008, 37.0)
(180, 'Valentino Rossi', 'Italy', 9, '>10', 'motorcycle gp', 2008, 35.0)
(181, 'Roger Federer', 'Switzerland', 9, '>10', 'tennis', 2008, 35.0)
(182, 'Tiger Woods', 'USA', 1, '1', 'golf', 2009, 110.0)
(183, 'Kobe Bryant', 'USA', 2, '6', 'basketball', 2009, 45.0)
(184, 'Michael Jordan', 'USA', 2, '3', 'basketball', 2009, 45.0)
(185, 'Kimi Raikkonen', 'Finland', 2, '5', 'F1 racing', 2009, 45.0)
(186, 'David Beckham', 'UK', 5, '2', 'soccer', 2009, 42.0)
(187, 'LeBron James', 'USA', 6, '7', 'basketball', 2009, 40.0)
(188, 'Phil Mickelson', 'USA', 6, '3', 'golf', 2009, 40.0)
(189, 'Manny Pacquiao', 'Philippines', 6, '>10', 'boxing', 2009, 40.0)
(190, 'Valentino Rossi', 'Italy', 9, '9', 'motorcycle gp', 2009, 35.0)
(191, 'Dale Earnhardt Jr.', 'USA', 10, '>10', 'NASCAR', 2009, 34.0)
(192, 'Tiger Woods', 'USA', 1, '1', 'golf', 2010, 105.0)
(193, 'Floyd Mayweather', 'USA', 2, '>10', 'boxing', 2010, 65.0)
(194, 'Kobe Bryant', 'USA', 3, '2', 'basketball', 2010, 48.0)
(195, 'Phil Mickelson', 'USA', 4, '6', 'golf', 2010, 46.0)
(196, 'David Beckham', 'UK', 5, '5', 'soccer', 2010, 43.7)
(197, 'Roger Federer', 'Switzerland', 6, '>10', 'tennis', 2010, 43.0)
(198, 'LeBron James', 'USA', 7, '6', 'basketball', 2010, 42.8)
(199, 'Manny Pacquiao', 'Philippines', 8, '6', 'boxing', 2010, 42.0)
(200, 'Eli Manning', 'USA', 9, '>10', 'American Football', 2010, 39.9)
(201, 'Terrell Suggs', 'USA', 10, '>10', 'American Football', 2010, 38.3)
(202, 'Tiger Woods', 'USA', 1, '1', 'golf', 2011, 75.0)
(203, 'Kobe Bryant', 'USA', 2, '3', 'basketball', 2011, 53.0)
(204, 'LeBron James', 'USA', 3, '7', 'basketball', 2011, 48.0)
(205, 'Roger Federer', 'Switzerland', 4, '6', 'tennis', 2011, 47.0)
(206, 'Phil Mickelson', 'USA', 5, '4', 'golf', 2011, 46.5)
(207, 'David Beckham', 'UK', 6, '5', 'soccer', 2011, 40.0)
(208, 'Cristiano Ronaldo', 'Portugal', 7, '13', 'soccer', 2011, 38.0)
(209, 'Alex Rodriguez', 'Dominican', 8, '12', 'baseball', 2011, 35.0)
(210, 'Michael Schumacher', 'Germany', 9, '>20', 'F1 racing', 2011, 34.0)
(211, 'Lionel Messi', 'Argentina', 10, '>20', 'soccer', 2011, 32.3)
(212, 'Floyd Mayweather', 'USA', 1, '?', 'Boxing', 2012, 85.0)
(213, 'Manny Pacquiao', 'Filipino', 2, '24', 'Boxing', 2012, 62.0)
(214, 'Tiger Woods', 'USA', 3, '1', 'Golf', 2012, 59.4)
(215, 'LeBron James', 'USA', 4, '3', 'Basketball', 2012, 53.0)
(216, 'Roger Federer', 'Switzerland', 5, '4', 'Tennis', 2012, 52.7)
(217, 'Kobe Bryant', 'USA', 6, '2', 'Basketball', 2012, 52.3)
(218, 'Phil Mickelson', 'USA', 7, '5', 'Golf', 2012, 47.8)
(219, 'David Beckham', 'UK', 8, '6', 'Soccer', 2012, 46.0)
(220, 'Cristiano Ronaldo', 'Portugal', 9, '21', 'Soccer', 2012, 42.5)
(221, 'Peyton Manning', 'USA', 10, '7', 'American Football', 2012, 42.4)
(222, 'Tiger Woods', 'USA', 1, '3', 'Golf', 2013, 78.1)
(223, 'Roger Federer', 'Switzerland', 2, '5', 'Tennis', 2013, 71.5)
(224, 'Kobe Bryant', 'USA', 3, '6', 'Basketball', 2013, 61.9)
(225, 'LeBron James', 'USA', 4, '4', 'Basketball', 2013, 59.8)
(226, 'Drew Brees', 'USA', 5, '?', 'American Football', 2013, 51.0)
(227, 'Aaron Rodgers', 'USA', 6, '?', 'American Football', 2013, 49.0)
(228, 'Phil Mickelson', 'USA', 7, '7', 'Golf', 2013, 48.7)
(229, 'David Beckham', 'UK', 8, '8', 'Soccer', 2013, 47.2)
(230, 'Cristiano Ronaldo', 'Portugal', 9, '9', 'Soccer', 2013, 44.0)
(231, 'Lionel Messi', 'Argentina', 10, '11', 'Soccer', 2013, 41.3)
(232, 'Floyd Mayweather', 'USA', 1, '14', 'Boxing', 2014, 105.0)
(233, 'Cristiano Ronaldo', 'Portugal', 2, '9', 'Soccer', 2014, 80.0)
(234, 'LeBron James', 'USA', 3, '4', 'Basketball', 2014, 72.3)
(235, 'Lionel Messi', 'Argentina', 4, '10', 'Soccer', 2014, 64.7)
(236, 'Kobe Bryant', 'USA', 5, '3', 'Basketball', 2014, 61.5)
(237, 'Tiger Woods', 'USA', 6, '1', 'Golf', 2014, 61.2)
(238, 'Roger Federer', 'Switzerland', 7, '2', 'Tennis', 2014, 56.2)
(239, 'Phil Mickelson', 'USA', 8, '7', 'Golf', 2014, 53.2)
(240, 'Rafael Nadal', 'Spain', 9, '>14', 'Tennis', 2014, 44.5)
(241, 'Matt Ryan', 'USA', 10, '>100', 'American Football', 2014, 43.8)
(242, 'Floyd Mayweather', 'USA', 1, '1', 'Boxing', 2015, 300.0)
(243, 'Manny Pacquiao', 'Philippines', 2, '11', 'Boxing', 2015, 160.0)
(244, 'Cristiano Ronaldo', 'Portugal', 3, '2', 'Soccer', 2015, 79.6)
(245, 'Lionel Messi', 'Argentina', 4, '4', 'Soccer', 2015, 73.8)
(246, 'Roger Federer', 'Switzerland', 5, '7', 'Tennis', 2015, 67.0)
(247, 'LeBron James', 'USA', 6, '3', 'Basketball', 2015, 64.8)
(248, 'Kevin Durant', 'USA', 7, '20', 'Basketball', 2015, 54.2)
(249, 'Phil Mickelson', 'USA', 8, '8', 'Golf', 2015, 50.8)
(250, 'Tiger Woods', 'USA', 9, '6', 'Golf', 2015, 50.6)
(251, 'Kobe Bryant', 'USA', 10, '5', 'Basketball', 2015, 49.5)
(252, 'Cristiano Ronaldo', 'Portugal', 1, '3', 'Soccer', 2016, 88.0)
(253, 'Lionel Messi', 'Argentina', 2, '4', 'Soccer', 2016, 81.4)
(254, 'LeBron James', 'USA', 3, '6', 'Basketball', 2016, 77.2)
(255, 'Roger Federer', 'Switzerland', 4, '5', 'Tennis', 2016, 67.8)
(256, 'Kevin Durant', 'USA', 5, '7', 'Basketball', 2016, 56.2)
(257, 'Novak Djokovic', 'Serbia', 6, '13', 'Tennis', 2016, 55.8)
(258, 'Cam Newton', 'USA', 7, '>20', 'American Football', 2016, 53.1)
(259, 'Phil Mickelson', 'USA', 8, '8', 'Golf', 2016, 52.9)
(260, 'Jordan Spieth', 'USA', 9, '>20', 'Golf', 2016, 52.8)
(261, 'Kobe Bryant', 'USA', 10, '10', 'Basketball', 2016, 50.0)
(262, 'Cristiano Ronaldo', 'Portugal', 1, '1', 'Soccer', 2017, 93.0)
(263, 'LeBron James', 'USA', 2, '3', 'Basketball', 2017, 86.2)
(264, 'Lionel Messi', 'Argentina', 3, '2', 'Soccer', 2017, 80.0)
(265, 'Roger Federer', 'Switzerland', 4, '4', 'Tennis', 2017, 64.0)
(266, 'Kevin Durant', 'USA', 5, '5', 'Basketball', 2017, 60.6)
(267, 'Andrew Luck', 'USA', 6, None, 'American Football', 2017, 50.0)
(268, 'Rory McIlroy', 'Northern Ireland', 6, '17', 'Golf', 2017, 50.0)
(269, 'Stephen Curry', 'USA', 8, None, 'Basketball', 2017, 47.3)
(270, 'James Harden', 'USA', 9, None, 'Basketball', 2017, 46.6)
(271, 'Lewis Hamilton', 'UK', 10, None, 'auto racing', 2017, 46.0)
(272, 'Floyd Mayweather', 'USA', 1, '>100', 'Boxing', 2018, 285.0)
(273, 'Lionel Messi', 'Argentina', 2, '3', 'Soccer', 2018, 111.0)
(274, 'Cristiano Ronaldo', 'Portugal', 3, '1', 'Soccer', 2018, 108.0)
(275, 'Conor McGregor', 'Ireland', 4, '24', 'MMA', 2018, 99.0)
(276, 'Neymar', 'Brazil', 5, '18', 'Soccer', 2018, 90.0)
(277, 'LeBron James', 'USA', 6, '2', 'Basketball', 2018, 85.5)
(278, 'Roger Federer', 'Switzerland', 7, '4', 'Tennis', 2018, 77.2)
(279, 'Stephen Curry', 'USA', 8, '8', 'Basketball', 2018, 76.9)
(280, 'Matt Ryan', 'USA', 9, '>100', 'American Football', 2018, 67.3)
(281, 'Matthew Stafford', 'USA', 10, '>100', 'American Football', 2018, 59.5)
(282, 'Lionel Messi', 'Argentina', 1, '2', 'Soccer', 2019, 127.0)
(283, 'Cristiano Ronaldo', 'Portugal', 2, '3', 'Soccer', 2019, 109.0)
(284, 'Neymar', 'Brazil', 3, '5', 'Soccer', 2019, 105.0)
(285, 'Canelo Alvarez', 'Mexico', 4, '15', 'Boxing', 2019, 94.0)
(286, 'Roger Federer', 'Switzerland', 5, '7', 'Tennis', 2019, 93.4)
(287, 'Russell Wilson', 'USA', 6, '??', 'American Football', 2019, 89.5)
(288, 'Aaron Rogers', 'USA', 7, '??', 'American Football', 2019, 89.3)
(289, 'LeBron James', 'USA', 8, '6', 'Basketball', 2019, 89.0)
(290, 'Stephen Curry', 'USA', 9, '8', 'Basketball', 2019, 79.8)
(291, 'Kevin Durant', 'USA', 10, '11', 'Basketball', 2019, 65.4)
(292, 'Roger Federer', 'Switzerland', 1, '5', 'Tennis', 2020, 106.3)
(293, 'Cristiano Ronaldo', 'Portugal', 2, '2', 'Soccer', 2020, 105.0)
(294, 'Lionel Messi', 'Argentina', 3, '1', 'Soccer', 2020, 104.0)
(295, 'Neymar', 'Brazil', 4, '3', 'Soccer', 2020, 95.5)
(296, 'LeBron James', 'USA', 5, '8', 'Basketball', 2020, 88.2)
(297, 'Stephen Curry', 'USA', 6, '9', 'Basketball', 2020, 74.4)
(298, 'Kevin Durant', 'USA', 7, '10', 'Basketball', 2020, 63.9)
(299, 'Tiger Woods', 'USA', 8, '11', 'Golf', 2020, 62.3)
(300, 'Kirk Cousins', 'USA', 9, '>100', 'American Football', 2020, 60.5)
(301, 'Carson Wentz', 'USA', 10, '>100', 'American Football', 2020, 59.1)